name: Build Desktop App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Nativefier
        # একদম পুরনো স্ট্যাবল ভার্সন ইন্সটল করছি
        run: npm install -g nativefier@43.0.0

      - name: Build App
        # এখানে Electron v11.4.4 ফিক্স করে দেওয়া হয়েছে যা Windows 7 সাপোর্ট করে
        run: nativefier --name "VDOSkyApp" "https://appcreator05.github.io/update/" --platform windows --arch x64 --electron-version 11.4.4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VDOSkyApp-Windows
          path: VDOSkyApp-win32-x64/
